apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipelines
resources:
# applications
- apps

configMapGenerator:
  # apps1
  - name: cicd-apps1
    files:
      - values.yaml=projects/modules/values.yaml
            
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated