{{- $Tasks := .Values.Tasks.securityTest }}
{{- if $Tasks.enabled -}}
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: security-test
spec:
  steps:
    - name: security-test
      image: alpine
      command:
        - echo
      args:
        - "Run security-test"
{{- end }}