apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipelines
resources:
# modules
- modules/release.yaml

configMapGenerator:
  # modules
  - name: cicd-modules
    files:
      - values.yaml=projects/modules/values.yaml
            
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated